### ISSUE TITLE
Fatal error on template

### ISSUE THREAD

**Issue by zuiko** [integer-net/IntegerNet_AttributeOptionPager#1]
Hi
I was very interested in using this extension but under magento 1.4.1.1 release. I know it's very old but it's also very expensive to upgrade and I maintain it against security and compatibility issues.
Testing this extension on an attribute I have got a fatal error on the template :  on the first line code <?php if($this->getCollection()->getSize()): ?> 
The error says : tying getSize() on a non object
I tried to find something to help in the code but nothing obvious. Maybe the toolbar block is not loaded correctly?
 Have a good day.

**Comment by schmengler** [comment]
I'm sorry but as the readme states, the extension requires at least Magento 1.6 - the tests fail on 1.5 and I don't have the intention to ensure backwards compatibility that far. Feel free to create a fork for Magento 1.4, if you have success with it, I'll link it here.

But I cannot tell you what exactly needs to be changed. The blocks are probably structured in a different way in these versions.

**Comment by zuiko** [comment]
I understand,
many post 1.4.1.1 extensions are working well on 1.4.1.1 even with blocks but I will search a bit if I find time. 
(I use also Jarlssen_FasterAttributeOptionEdit which is perfect for mys numerous values attributes!).
Have a good day.
