### ISSUE TITLE
Magento 2.x Support

### ISSUE THREAD

**Issue by zahedm** [integer-net/IntegerNet_AttributeOptionPager#2]
Hi,
Does this work on Magento 2.X ?
If you have a different solution for Magento 2.X please provide details.

**Comment by schmengler** [comment]
Sorry, no. It is a Magento 1 extension. I don't even know, if the issues it solves are prevalent on Magento 2

**Comment by norgeindian** [comment]
I found a lot of posts where the same problem was described for M2. Did not try it by myself, but it seems as if it is not solved there as well.

**Comment by zahedm** [comment]
Ole,

Sounds great.

Please share an M2 version of the extension.

 

 

Regards,

Zahed
